name: hotel_tv_launcher
description: Hotel TV launcher for Android TV and Samsung Tizen.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_riverpod: ^2.6.1
  dio: ^5.8.0+1
  web_socket_channel: ^3.0.2
  shared_preferences: ^2.3.5
  cached_network_image: ^3.4.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
